name = "FgankNewMods"
author = "lre0550"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a41e74e6d034d592cb80787bd1d21701ea50607764dd787d43b2bd99d753413c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
