name = "FgankNewMods"
author = "lre0550"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1096a31a6c82caa8f5340703b3ce76bcfebab5644834cbf505cd278dfbc49e2d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
