name = "FgankNewMods"
author = "lre0550"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa59374b3ec8afbadede451dcec64ee8c4a18ff7490406ee3b401e55ba1aad81"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
